syntax on
set nocompatible
set autoindent
set ruler
set tabstop=4 softtabstop=0 noexpandtab shiftwidth=4
set hidden
set wildmode=longest,list,full
set wildmenu
" prevent escape delay
set esckeys

execute pathogen#infect()
filetype plugin indent on
" " Begin Vundle
" filetype off
" set rtp+=~/.vim/bundle/Vundle.vim
" 
" call vundle#begin()
" Plugin 'gmarik/Vundle.vim'
" Plugin 'tpope/vim-fugitive'
" Plugin 'vim-syntastic/syntastic'
" Plugin 'pangloss/vim-javascript'
" Plugin 'leafgarland/typescript-vim'
" call vundle#end()
" filetype plugin indent on
" " End Vundle

function ShowSpaces(...)
	let @/='\v(\s+$)|( +\ze\t)'
	let oldhlsearch=&hlsearch
	if !a:0
		let &hlsearch=!&hlsearch
	else
		let &hlsearch=a:1
	end
	return oldhlsearch
endfunction

function TrimSpaces() range
	let oldhlsearch=ShowSpaces(1)
	execute a:firstline.",".a:lastline."substitute ///gec"
	let &hlsearch=oldhlsearch
endfunction

command -bar -nargs=? ShowSpaces call ShowSpaces(<args>)
command -bar -nargs=0 -range=% TrimSpaces <line1>,<line2>call TrimSpaces()
nnoremap <F9> :ShowSpaces 1<CR>
nnoremap <S-F9> m`:TrimSpaces<CR>``

" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" typescript syntastic
let g:tsuquyomi_disable_quickfix = 1
let g:syntastic_typescript_checkers = ['tsuquyomi'] " You shouldn't use 'tsc' checker.
